# These are supported funding model platforms

github: tofiqquadri# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: tofiqquadri # Replace with a single Patreon username
